### ISSUE TITLE
 python 3.6 didn't support the numpy 1.22.0

### ISSUE THREAD

**Issue by 1987521** [yqlbu/TRT-yolov3#11]
numpy 1.22.0 requires python 3.8~3.11. In the installation, the python 3.6 didn't support the numpy 1.22.0
<img width="1074" alt="屏幕截图 2022-11-02 225153" src="https://user-images.githubusercontent.com/95991721/199522144-d33c149a-2a7e-4f64-851f-6714e0e7b731.png">

**Comment by piyoki** [comment]
@1987521  This repo is no-longer under maintenance. However, I reverted the dependencies to where I started off the project. Please check the `requirements.txt` file.
